### PR TITLE
Add convert script and table of ROM info

### PR DESCRIPTION
**Pull request by kbembedded**
Simple shell script and CSV table of ROM info. The table is based on the text file from TerraOnion and therefore includes definitions for every ROM set supported. This table contains the common ROM set name, TO's proprietary screenshot number, the NGH number, the English title, genre, publish year, developer, and a parent ROM (if applicable). I've tested with about 2 dozen games but the table is as filled out as I could make it.

The script takes a single ROM set archive or directory containing multiple ROM set archives, looks them up in the table, and runs neosdconv against them with the proper arguments.

1. I'm not sure if this belongs as a part of your project, feel free to reject and state it as such. This is definitely outside of the scope of neosdconv, as well as your goal for the project. However, on the other side, the script and table are pretty much useless without neosdconv. If you don't think its in scope here, I'll slap these in their own repo and call it good.

2. The script is pretty rough, it was meant as a quick way to not have to type in the args every time to neosdconv. For that purpose it works. It does not support child ROMs that require a parent, and I have no plans to take it to that point for a number of reasons. On a technical level, the ROM set distributions and file names are too variable to be handled by this simple script. It would be more manageable if the script and table used checksums. Using a more powerful scripting language would probably be wise here too.

3. In order to implement checksums, the script and the table would need to be expanded quite a bit. In this case, it would probably be a worthy goal to scrape the info from NeoBuilder or a site like the arcade database. But, as it is, the script and table have worked for every parent ROM I've tested. This includes a couple ROMs that were not in the NeoBuilder text file originally.

### CODE REVIEW

**Comment by city41** [comment]
This is great! Thanks for doing this. I don't mind this being in the main repo. I like that the script just uses neosdconv's command line interface, keeping the two nice and separate.

**Comment by city41** [comment]
I added a note about this script in the README.

Adding checksums would be nice down the road. But this is still super useful as-is, so I'm not too worried about them right now.

**Comment by kbembedded** [comment]
Cool :D

But also, I wanted to note that your changes to the README are not quite correct. The .csv needs to be in the same folder in the script, OR more args passed and the csv specified as the last argument e.g. `cd scripts && ./convert.sh <dir of ROMs>` or `./scripts/convert.sh <dir of ROMs> <output dir for .neo files> ./scripts/neosd_romset.csv`

That behavior is the same when specifying a single ROM set zip as well. e.g. `cd scripts && ./convert.sh input.zip` or `./scripts/convert.sh /path/to/input.zip /path/to/output/dir/ ./scripts/neosd_romset.csv`

I can change this behavior if you think thats easier. Would add a search path of `./` and `./scripts/` first

**Comment by city41** [comment]
Ah ok. I added an extra sentence to the README:

```
The script is flexible on the locations of the input roms, output folder and the location of the csv file. For more information, run `convert.sh` without any arguments for help.
```

**Pull request merged**
